### ISSUE TITLE
Vast-tools and diff starting with BAM files

### ISSUE THREAD

**Issue by Rahel14350** [vastgroup/vast-tools#43]
Dear Tim,

I have a big stranded RNA-seq data set from human (10 conditions and 50 samples). I want to use Vast-tools and diff for differential alternative splicing analysis and estimation of intron retention/exon skipping in my data set.

As far as I checked, the Vast-tools starting from fastq files and alignment.
I did already mapped the reads with TopHat2. Is it possible to start Vast-tools with uploading the BAM files?

The reason I would use the BAM files from TopHat2 is to have the same input for all the analysis I already did like DeSeq2 and DEXSeq, and also because I tried bowtie with raw reads once in other R package and I get huge amount of unmapped reads (more than 90%).
Do you think still it is possible and reasonable to start the program with BAM files?

Many thanks in advance for your help,

Kind Regards,
Rahel

**Comment by timbitz** [comment]
You will not be able to use exterior BAM files with vast-tools.  It has its own database of predefined splice junctions that the reads are aligned to in order to determine percent-spliced-in.  This is a major difference between DEXseq which I do not think uses splice junctions at all.  Therefore, the output is likely to differ based upon fundamental differences in what the two programs consider relevant information towards inference of alternative splicing levels.

Good luck! 

ps. Tophat2 uses bowtie/bowtie2 for alignment also...

**Comment by Rahel14350** [comment]
Dear Tim,
Many thanks for prompt reply. I am going to start Vast with Fastq reads.

Kind Regards,
Raheleh

**Comment by Rahel14350** [comment]
Dear Tim,
I was successful to install Vast-tools on the server and I am doing aligning currently. As I have 10 levels of data and afterwards I need to do differential splicing analysis on the output data. Do you recommend me still to use Diff? Or is it possible to import IR counts or exon skipped counts in DESeq2 and do the differential analysis there? 

Many thanks in advance,
Raheleh

**Comment by Rahel14350** [comment]
Dear Tim,

I did post some question on the vasttols issues. Your answers will be so
helpful for me.
I am so grateful for your time and help.

Kind Regards,
Rahel

On Wed, Sep 9, 2015 at 11:20 PM, Tim Sterne-Weiler <notifications@github.com

**Comment by timbitz** [comment]
#44
