### ISSUE TITLE
Align problem

### ISSUE THREAD

**Issue by danieleottaviani** [vastgroup/vast-tools#66]
Hi there,
I'm trying to align my fastq files but I'm stuck on an error I can't spot...please see below. 
The VastDB and all dependancies look OK. I tried fastq from different sources (i.e. SRA) but VAST-TOOLS gets stuck still (bowtie, by itself, seems able to align the fastq file). 
I'm working on a MacOS Sierra 10.12.6.
Thank you in advance for helping!

```
csc14:~ danieleottaviani$ vast-tools align /Users/danieleottaviani/vast-tools/Input/Index33_1.fastq.gz 
[vast align]: Input RNA-seq file(s): /Users/danieleottaviani/vast-tools/Input/Index33_1.fastq.gz
[vast align]: Most common read length detected for fq1: 126 (100.00%)
[vast align]: Using VASTDB -> /Users/danieleottaviani/vast-tools/VASTDB/Hsa
[vast align]: Setting output directory to /Users/danieleottaviani/vast_out
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to /Users/danieleottaviani/vast_out/tmp!
head: -: No such file or directory
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)
No alignments
Too few first reads (<500) could be mapped to mRNA library for detecting strand-orientation of reads. Maybe wrong species selected? at /Users/danieleottaviani/vast-tools/bin/RunDBS_1.pl line 463.
```

**Comment by mirimia** [comment]
Hey,

To be honest, we haven't really tested vast-tools on Mac, and I imagine this could be the issue. We'll try to get back to you ASAP.

@aghr: could you please take a look? 

M

**Comment by aghr** [comment]
Dear Daniele,

Many thanks for reporting this issue. The problem seems to be how vast-tools invokes head in a pipe. On Unix this works:  "cat dummy.txt | head -n 2 - | cat" whereas on MacOS this seems to give the error message "head: -: No such file or directory". Though, "cat dummy.txt | head -n 2 | cat" seems to work on both systems. 

Hence, I have changed two pipe commands where I have removed the "-" from the call of head. You could checkout vast-tools by git pull origin master. When you have more issues, you might get in touch with us directly by sending an Email to andre.gohr@crg.eu .

Many thanks again.

**Comment by danieleottaviani** [comment]
Dear Andre,
That's great, it seems to be working fine now!
Many Thanks!
