### ISSUE TITLE
low alignment rates

### ISSUE THREAD

**Issue by imendizabalCIC** [vastgroup/vast-tools#88]
Hi,

I have run vast-align on my RNAseq data (55 million reads per sample, paired end 150bp and human genome) and found that the alignment rates are around 45% (please see below). I am surprised, since I had previously got >85% alignment rates with STAR on the same fastq files and genome version. I have been able to run downstream AS analyses with vast-tools on my data but found that the coverage is too low for most events (quality scores below minimum threshold or "N"). 

My libraries are stranded so I thought the problem could be in the automatic detection of strand-specific libraries by vast-tools align, but when I specify "--rc1 --nrc2" the rates look similar.  I would really appreciate if you have any suggestion on how I can improve the low alignment rates.

My command:
./vast-tools align /storage/Shared/Merged_AC-27/DOX24H_1_R1.fastq.gz /storage/Shared/Merged_AC-27/DOX24H_1_R2.fastq.gz -sp hg38 -c 8

[vast align]: VAST-TOOLS v2.4.1
[vast align]: Species assembly: hg38, VASTDB Species key: Hs2
[vast align]: VASTDB Version: vastdb.hs2.20.12.19
[vast align]: Input RNA-seq file(s): /storage/Shared/Merged_AC-27/DOX24H_1_R1.fastq.gz and /storage/Shared/Merged_AC-27/DOX24H_1_R2.fastq.gz
[vast align]: Most common read lengths detected for fq1 & fq2: 151 (100.00%) and 151 (100.00%)
[vast align]: Sample name: DOX24H_1_R1
[vast align]: Using VASTDB -> /storage/AClab/AC-27_RNAseq_splicing/vast-tools/vast-tools-2.4.1/VASTDB/Hs2
[vast align]: Setting output directory to /storage/AClab/AC-27_RNAseq_splicing/vast-tools/vast-tools-2.4.1/vast_out
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to /storage/AClab/AC-27_RNAseq_splicing/vast-tools/vast-tools-2.4.1/vast_out/tmp!
 reads processed: 500000
 reads with at least one reported alignment: 219687 (43.94%)
 reads that failed to align: 274781 (54.96%)
 reads with alignments suppressed due to -m: 5532 (1.11%)
Reported 219687 alignments
[vast align]:    fraction of first reads mapping to fwd / rev strand : 0.0045 / 0.9955
 reads processed: 500000
 reads with at least one reported alignment: 217945 (43.59%)
 reads that failed to align: 276665 (55.33%)
reads with alignments suppressed due to -m: 5390 (1.08%)
Reported 217945 alignments
[vast align]:    fraction of second reads mapping to fwd / rev strand : 0.9954 / 0.0046
[vast align]:    reverse-complementing reads from /storage/Shared/Merged_AC-27/DOX24H_1_R1.fastq.gz; writing into /storage/AClab/AC-27_RNAseq_splicing/vast-tools/vast-tools-2.4.1/vast_out/tmp/tmpfqs_VxeOqqef/DOX24H_1_R1.fastq.gz
[vast align]: Trimming RNAseq reads to 50 nt sequences
[vast trim]: Total processed reads: 57703065
[vast trim]: Total valid fwd reads: 57703065
[vast trim]: Total valid rev reads: 57703065
[vast align]: Doing genome subtraction

Thank you very much in advance!

Isabel

**Comment by mirimia** [comment]
Hi Isabel,

Can you please also paste the % alignment for the genome (the one that comes right after what you pasted)?

These mappings for those categories are not too bad (perhaps it may suggest you have a relatively high amount of IR, pre-mRNA and/or rRNA). Please keep in mind that vast-tools maps directly to pre-built junctions later on, and those are the ones used for PSI calculations, so the % mappings it provides in the first steps are not equivalent to those you get with STAR (i.e. VTS ones are always lower). You get higher % of mapping using STAR because it's junction-aware. Here, by construction, only % mapping with no junctions are reported.

RE the high number of Ns, that I'm afraid this is also related to the number of reads you're using. 55M is not a lot for an AS analyses. Ideally, you want to go for >100M. Still, you should be able to get decent PSIs for quite a few events...

Best
Manu

**Comment by imendizabalCIC** [comment]
Hi Manu,

Thank you so much for your prompt response! Here the rest of the messages I get:

[vast align]: Doing genome subtraction
# reads processed: 577030650
# reads with at least one reported alignment: 313722792 (54.37%)
# reads that failed to align: 151966134 (26.34%)
# reads with alignments suppressed due to -m: 111341724 (19.30%)
Reported 313722792 alignments
[vast align]: Mapping reads to the "splice site-based" (aka "a posteriori") EEJ library and Analyzing...
# reads processed: 151966134
# reads with at least one reported alignment: 47995021 (31.58%)
# reads that failed to align: 100977343 (66.45%)
# reads with alignments suppressed due to -m: 2993770 (1.97%)
Reported 47995021 alignments
[vast align]: Mapping reads to the "transcript-based" (aka "a priori") SIMPLE EEJ library and Analyzing...
# reads processed: 151966134
# reads with at least one reported alignment: 7714595 (5.08%)
# reads that failed to align: 144093237 (94.82%)
# reads with alignments suppressed due to -m: 158302 (0.10%)
Reported 7714595 alignments
[vast align]: Mapping reads to the "transcript-based" (aka "a priori") MULTI EEJ library and Analyzing...
# reads processed: 151966134
# reads with at least one reported alignment: 19171332 (12.62%)
# reads that failed to align: 132058914 (86.90%)
# reads with alignments suppressed due to -m: 735888 (0.48%)
Reported 19171332 alignments
[vast align]: Mapping reads to microexon EEJ library and Analyzing...
# reads processed: 151966134
# reads with at least one reported alignment: 968243 (0.64%)
# reads that failed to align: 150865282 (99.28%)
# reads with alignments suppressed due to -m: 132609 (0.09%)
Reported 968243 alignments
[vast align]: Mapping reads to intron retention library (version 2)...
# reads processed: 577030650
# reads with at least one reported alignment: 64996476 (11.26%)
# reads that failed to align: 510109947 (88.40%)
# reads with alignments suppressed due to -m: 1924227 (0.33%)
Reported 64996476 alignments
# reads processed: 577030650
# reads with at least one reported alignment: 2938140 (0.51%)
# reads that failed to align: 570730885 (98.91%)
# reads with alignments suppressed due to -m: 3361625 (0.58%)
Reported 2938140 alignments
[vast align]: Cleaning DOX24H_1_R1-50.fa.gz files!
[vast align]: Cleaning up DOX24H_1_R1-50-e.fa.gz!
[vast align]: Deleting temporary files with reverse-complemented reads.

What you mention about IR would make a lot of sense, since these are data based on silencing a gene, which may affect splicing efficiency. I get 42% of IR out of all significant events (i.e.  non-zero MV.dPsi._at_0.95 values from vast-tools diff) and 32% among those with MV.dPsi._at_0.95 >10%. Perhaps these figures suggest high IR causing relatively low initial mapping rates?

Thanks again for you valuable insights. Best,

Isabel

**Comment by mirimia** [comment]
Hello,

Yes, this is possible. If you look at the % of genome mapping (excluding junctions), this is 54.37+19.30 = 73.7%. Then, to the junctions is 8.8% (very rough estimate). So this is ~82.5%.

The problem with having a lot of IR is that you would need even more coverage, since the fraction of reads mapping to intron bodies will be very high, and this will not be really used for anything (in most software).

Things you can do:
- run a `compare` test: this will give you a small summary. If you have a lot of IR, you will see a very high number for HIGH in the KO compared to HIGH in Control.
- you can merge the outputs of the replicates (if you have) to increase coverage using `merge`. You will get more coverage, although for a single "super-replicate". This will give you a good overview, though (e.g. in the summary output of compare).

Cheers
